# Tensors
## This script introduces various ways to create tensors in TensorFlow

First we start with loading TensorFlow and reseting the computational graph.

In [1]:
import tensorflow as tf
from tensorflow.python.framework import ops
ops.reset_default_graph()

### Start a graph session
Get graph handle with the tf.Session()

In [2]:
sess = tf.Session()

### Creating Tensors
TensorFlow has built in function to create tensors for use in variables.  For example, we can create a zero filled tensor of predefined shape using the `tf.zeros()` function as follows.

#### 1. 固定张量

In [4]:
my_tensor = tf.zeros([1,20])

We can evaluate tensors with calling a `run()` method on our session.

In [5]:
sess.run(my_tensor)

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.]], dtype=float32)

In [6]:
a = tf.ones([1, 2, 3])
sess.run(a)

array([[[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]], dtype=float32)

In [7]:
b = tf.fill([3, 5], 43)
sess.run(b)

array([[43, 43, 43, 43, 43],
       [43, 43, 43, 43, 43],
       [43, 43, 43, 43, 43]])

`tf.constant()`支持广播：(模拟`tf.fill()`的功能)

In [8]:
c = tf.constant([42, 32, 3, 4], shape= [4, 5])
sess.run(c)

array([[42, 32,  3,  4,  4],
       [ 4,  4,  4,  4,  4],
       [ 4,  4,  4,  4,  4],
       [ 4,  4,  4,  4,  4]])

#### 2. 相似形状的张量

In [19]:
a = tf.constant([2, 3, 4, 5], shape = [2, 2])
zeros_similar = tf.zeros_like(a)
sess.run(zeros_similar)

array([[0, 0],
       [0, 0]])

#### 3. 序列张量

In [25]:
le = tf.linspace(start= 0., stop= 1., num= 3)
sess.run(le)

array([ 0. ,  0.5,  1. ], dtype=float32)

In [28]:
lr = tf.range(start= 6, limit=15, delta=3) # 不包含15
sess.run(lr)

array([ 6,  9, 12])

#### 4. 随机张量

In [31]:
s1 = tf.random_uniform([2, 3], minval= 0, maxval= 1)
sess.run(s1)

array([[ 0.9079206 ,  0.69183397,  0.1184355 ],
       [ 0.08602607,  0.12508607,  0.99436617]], dtype=float32)

`tf.random_uniform()`随机均匀分布，$minval \leq x < maxval$

In [35]:
s2 = tf.random_normal([2, 3], mean=0., stddev= 1)  # 正太分布
sess.run(s2)

array([[ 1.17236924, -1.83960342,  0.42288613],
       [-2.37124944, -0.03283463, -0.18045625]], dtype=float32)

In [38]:
s3 = tf.truncated_normal([2, 3], mean=0., stddev= 1)  # 随机数位于均值到两个标准差之间的区间
sess.run(s3)

array([[-1.48957086,  0.98846173, -0.44041571],
       [ 0.75184584, -0.85215306,  0.57836169]], dtype=float32)

##### 张量/数组的随机化

In [39]:
q1 = tf.random_shuffle(tf.constant([3, 4, 5, 6]))
sess.run(q1)

array([6, 3, 5, 4])

##### `tf.random_crop()`实现张量的随机裁剪
比如：`tf.random_crop(my_image, [height/2, width/2, 3])`

In [62]:
q2 = tf.random_crop(tf.constant([[3, 4], [5, 6], [4, 6], [3, 7]]), size= [1, 1])
sess.run(q2)

array([[3]])

TensorFlow algorithms need to know which objects are variables and which are constants. The difference between these two objects will be explained later in the chapter. For now we create a variable using the TensorFlow function `tf.Variable()` as follows.（一旦创建好张量，就可以通过`tf.Variable()`函数来封装张量作为变量：）

In [5]:
my_var = tf.Variable(tf.zeros([1,20]))

Note that you can not run `sess.run(my_var)`, this would result in an error.  Because TensorFlow operates with computational graphs, we have to create a variable intialization operation in order to evaluate variables.  We will see more of this later on.  For this script, we can initialize one variable at a time by calling the variable method `my_var.initializer`.

In [6]:
sess.run(my_var.initializer)
sess.run(my_var)

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.]], dtype=float32)

##### `tf.convert_to_tensor()`函数

In [64]:
a1 = tf.convert_to_tensor(tf.constant([2, 3, 4, 5]))
sess.run(a1)

array([2, 3, 4, 5])

In [68]:
a2 = tf.convert_to_tensor([2, 3])
sess.run(a2)

array([2, 3])

Let's first start by creating variables of specific shape by declaring our row and column size.

In [70]:
row_dim = 2
col_dim = 3

Here are variables initialized to contain all zeros or ones.

In [71]:
zero_var = tf.Variable(tf.zeros([row_dim, col_dim]))
ones_var = tf.Variable(tf.ones([row_dim, col_dim]))

Again, we can call the initializer method on our variables and run them to evaluate thier contents.

In [72]:
sess.run(zero_var.initializer)
sess.run(ones_var.initializer)
print(sess.run(zero_var))
print(sess.run(ones_var))

[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]]


### Creating Tensors Based on Other Tensor's Shape
If the shape of a tensor depends on the shape of another tensor, then we can use the TensorFlow built-in functions `ones_like()` or `zeros_like()`.

In [73]:
zero_similar = tf.Variable(tf.zeros_like(zero_var))
ones_similar = tf.Variable(tf.ones_like(ones_var))
sess = tf.Session()
sess.run(tf.global_variables_initializer())
print(sess.run(ones_similar))
print(sess.run(zero_similar))

[[ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]]


In [74]:
zero_similar = tf.Variable(tf.zeros_like(zero_var))
ones_similar = tf.Variable(tf.ones_like(ones_var))

sess.run(ones_similar.initializer)
sess.run(zero_similar.initializer)
print(sess.run(ones_similar))
print(sess.run(zero_similar))

[[ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]]


### Filling a Tensor with a Constant
Here is how we fill a tensor with a constant.

In [11]:
fill_var = tf.Variable(tf.fill([row_dim, col_dim], -1))
sess.run(fill_var.initializer)
print(sess.run(fill_var))

[[-1 -1 -1]
 [-1 -1 -1]]


We can also create a variable from an array or list of constants.

In [12]:
# Create a variable from a constant
const_var = tf.Variable(tf.constant([8, 6, 7, 5, 3, 0, 9]))
# This can also be used to fill an array:
const_fill_var = tf.Variable(tf.constant(-1, shape=[row_dim, col_dim]))

sess.run(const_var.initializer)
sess.run(const_fill_var.initializer)

print(sess.run(const_var))
print(sess.run(const_fill_var))

[8 6 7 5 3 0 9]
[[-1 -1 -1]
 [-1 -1 -1]]


### Creating Tensors Based on Sequences and Ranges
We can also create tensors from sequence generation functions in TensorFlow.  The TensorFlow function `linspace()` and `range()` operate very similar to the python/numpy equivalents.

In [ ]:
# Linspace in TensorFlow
linear_var = tf.Variable(tf.linspace(start=0.0, stop=1.0, num=3)) # Generates [0.0, 0.5, 1.0] includes the end

# Range in TensorFlow
sequence_var = tf.Variable(tf.range(start=6, limit=15, delta=3)) # Generates [6, 9, 12] doesn't include the end

sess.run(linear_var.initializer)
sess.run(sequence_var.initializer)

print(sess.run(linear_var))
print(sess.run(sequence_var))

### Random Number Tensors
We can also initialize tensors that come from random numbers like the following.

In [ ]:
rnorm_var = tf.random_normal([row_dim, col_dim], mean=0.0, stddev=1.0)
runif_var = tf.random_uniform([row_dim, col_dim], minval=0, maxval=4)

print(sess.run(rnorm_var))
print(sess.run(runif_var))

### Visualizing the Variable Creation in TensorBoard
To visualize the creation of variables in Tensorboard (covered in more detail in Chapter 11), we will reset the computational graph and create a global initializing operation.

In [75]:
# Reset graph
ops.reset_default_graph()

# Start a graph session
sess = tf.Session()

# Create variable
my_var = tf.Variable(tf.zeros([1,20]))

# Add summaries to tensorboard
merged = tf.summary.merge_all()

# Initialize graph writer:
writer = tf.summary.FileWriter("/tmp/variable_logs", graph=sess.graph)

# Initialize operation
initialize_op = tf.global_variables_initializer()

# Run initialization of variable
sess.run(initialize_op)

We now run the following command in our command prompt:

`tensorboard --logdir=/tmp`

And it will tell us the URL we can navigate our browser to to see Tensorboard. The default should be:

`http://0.0.0.0:6006/`

In [ ]:
!tensorboard --logdir=/tmp

![Variable_in_Tensorboard](https://github.com/nfmcclure/tensorflow_cookbook/raw/master/01_Introduction/images/02_variable.png)