# Matrices and Matrix Operations

This function introduces various ways to create
matrices and how to use them in TensorFlow

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.python.framework import ops
ops.reset_default_graph()

Start a graph session

In [2]:
sess = tf.Session()

### Declaring matrices

Identity Matrix:

In [3]:
identity_matrix = tf.diag([1.0,1.0,1.0])
print(sess.run(identity_matrix))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


2x3 random norm matrix:

In [4]:
A = tf.truncated_normal([2,3])
print(sess.run(A))

[[-1.10683966 -0.43172005 -0.33894309]
 [-1.74352121  0.49193713 -0.45332393]]


2x3 constant matrix:

In [5]:
B = tf.fill([2,3], 5.0)
print(sess.run(B))

[[ 5.  5.  5.]
 [ 5.  5.  5.]]


3x2 random uniform matrix:

In [6]:
C = tf.random_uniform([3,2])
print(sess.run(C))

[[ 0.10744166  0.04911888]
 [ 0.32943428  0.18506098]
 [ 0.38936305  0.70674193]]


Create matrix from np array:

In [7]:
D = tf.convert_to_tensor(np.array([[1., 2., 3.], [-3., -7., -1.], [0., 5., -2.]]))
print(sess.run(D))

[[ 1.  2.  3.]
 [-3. -7. -1.]
 [ 0.  5. -2.]]


### Matrix Operations

Matrix addition/subtraction:

In [8]:
print(sess.run(A+B))
print(sess.run(B-B))

[[ 6.31514835  4.77878523  3.99692869]
 [ 6.90703821  6.91409588  6.0385251 ]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]]


Matrix Multiplication:

In [9]:
print(sess.run(tf.matmul(B, identity_matrix)))

[[ 5.  5.  5.]
 [ 5.  5.  5.]]


Matrix Transpose:

In [11]:
print(sess.run(tf.transpose(C)))

[[ 0.80337954  0.02286756  0.71371317]
 [ 0.34483409  0.42599761  0.31290567]]


Matrix Determinant:

In [12]:
print(sess.run(tf.matrix_determinant(D)))

-38.0


Matrix Inverse:

In [14]:
print(sess.run(tf.matrix_inverse(D)))

[[-0.5        -0.5        -0.5       ]
 [ 0.15789474  0.05263158  0.21052632]
 [ 0.39473684  0.13157895  0.02631579]]


Cholesky Decomposition:

In [15]:
print(sess.run(tf.cholesky(identity_matrix)))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


Eigenvalues and Eigenvectors:  We use `tf.self_adjoint_eig()` function, which returns two objects, first one is an array of eigenvalues, the second is a matrix of the eigenvectors.

In [16]:
eigenvalues, eigenvectors = sess.run(tf.self_adjoint_eig(D))
print(eigenvalues)
print(eigenvectors)

[-10.65907521  -0.22750691   2.88658212]
[[ 0.21749542  0.63250104 -0.74339638]
 [ 0.84526515  0.2587998   0.46749277]
 [-0.4880805   0.73004459  0.47834331]]
